### ISSUE TITLE
Indicate changes for the ATMega328p version

### ISSUE THREAD

**Issue by con-f-use** [tinyusbboard/selftest_defaultfirmware#1]
Please indicate the changes in firmware that have to be made for the "rare ATmega328p special edition" of the tinyusbboard. Or even better, have the makefile handle it automatically, when "DEVICE = atmega328p" is selected. Thank you!

**Comment by baerwolf** [comment]
Hi con-f-use.
Thx for your interest in tinyUSBboard.
What firmware do you mean?
The default firmware (the bootloader and the selftest firmware) both should have this feature.
The bootloader: Makefile.inc
The selftest: Makefile

I am really happy about your feedback.

BR Stephan

**Comment by con-f-use** [comment]
Maybe I didn't see it. I was just thrown off by the `DEVICE = atmega8` and the lack of fuse bits, if directives and the such in the Makefile of the "selftest_dafaultfirmware" here: https://github.com/tinyusbboard/selftest_defaultfirmware/blob/master/Makefile

Could it be, that the exact same firmware works on the ATMega328 without amy changes?

**Comment by baerwolf** [comment]
Using the USB interface does not need fusebits, since they always stay the same from (externally) programming the bootloader.
Therefore the only firmware, directly designed for tinyUSBboard, specifying fuse- and lockbits is the bootloader. ("make fuse"). There these bits are selected automatically by the makefile script based on the device.

> Could it be, that the exact same firmware works on the ATMega328 without amy changes?

Yes. These firmwares are mostly AVR independend implemented. Where neccessary, conditional compilation is used.

BR (and gn8) Stephan

**Comment by tinyusbboard** [comment]
I assume problem is solved.
